version: 2

before:
  hooks:
    - go mod download

builds:
  - id: "imuad-darwin"
    main: ./cmd/imuad
    binary: imuad
    env:
      - CGO_ENABLED=1
      - CC=o64-clang
      - CXX=o64-clang++
    goos:
      - darwin
    goarch:
      - amd64
    flags:
      - -tags=cgo
    ldflags:
      - -s -w -X github.com/cosmos/cosmos-sdk/version.Name=imua -X github.com/cosmos/cosmos-sdk/version.AppName=imuad -X github.com/cosmos/cosmos-sdk/version.Version={{.Version}} -X github.com/cosmos/cosmos-sdk/version.Commit={{.Commit}}
  - id: "imuad-darwin-arm64"
    main: ./cmd/imuad
    binary: imuad
    env:
      - CGO_ENABLED=1
      - CC=oa64-clang
      - CXX=oa64-clang++
    goos:
      - darwin
    goarch:
      - arm64
    flags:
      - -tags=cgo
    ldflags:
      - -s -w -X github.com/cosmos/cosmos-sdk/version.Name=imua -X github.com/cosmos/cosmos-sdk/version.AppName=imuad -X github.com/cosmos/cosmos-sdk/version.Version={{.Version}} -X github.com/cosmos/cosmos-sdk/version.Commit={{.Commit}}
  - id: "imuad-linux"
    main: ./cmd/imuad
    binary: imuad
    env:
      - CGO_ENABLED=1
      - CC=gcc
      - CXX=g++
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -tags=cgo
    ldflags:
      - -s -w -X github.com/cosmos/cosmos-sdk/version.Name=imua -X github.com/cosmos/cosmos-sdk/version.AppName=imuad -X github.com/cosmos/cosmos-sdk/version.Version={{.Version}} -X github.com/cosmos/cosmos-sdk/version.Commit={{.Commit}}
  - id: "imuad-linux-arm64"
    main: ./cmd/imuad
    binary: imuad
    env:
      - CGO_ENABLED=1
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
    goos:
      - linux
    goarch:
      - arm64
    flags:
      - -tags=cgo
    ldflags:
      - -s -w -X github.com/cosmos/cosmos-sdk/version.Name=imua -X github.com/cosmos/cosmos-sdk/version.AppName=imuad -X github.com/cosmos/cosmos-sdk/version.Version={{.Version}} -X github.com/cosmos/cosmos-sdk/version.Commit={{.Commit}}
  - id: "imuad-windows"
    main: ./cmd/imuad
    binary: imuad
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    goos:
      - windows
    goarch:
      - amd64
    flags:
      - -tags=cgo
      - -buildmode=exe
    ldflags:
      - -s -w -X github.com/cosmos/cosmos-sdk/version.Name=imua -X github.com/cosmos/cosmos-sdk/version.AppName=imuad -X github.com/cosmos/cosmos-sdk/version.Version={{.Version}} -X github.com/cosmos/cosmos-sdk/version.Commit={{.Commit}}

archives:
  - name_template: '{{ .ProjectName }}_{{ .Version }}_{{- title .Os }}_{{ .Arch }}'
    format_overrides:
      - goos: windows
        format: zip
    builds:
      - imuad-darwin
      - imuad-darwin-arm64
      - imuad-windows
      - imuad-linux
      - imuad-linux-arm64
  
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
snapshot:
  name_template: "{{ .Tag }}-{{ .Branch }}@{{ .ShortCommit }}-{{ .GitTreeState }}"

dockers:
  - id: ghcr-amd64
    skip_push: "{{ .IsSnapshot }}"
    use: buildx
    dockerfile: Dockerfile.ci
    ids: ["imuad-linux"]
    image_templates:
      - "ghcr.io/imua-xyz/imuachain:{{ .Tag }}-amd64"
      - '{{ if not (contains .Tag "-") }}ghcr.io/imua-xyz/imuachain:latest-amd64{{ end }}'
    goos: linux
    goarch: amd64
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.source={{ .GitURL }}"
      - "--label=org.opencontainers.image.revision={{ .Commit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.created={{ time \"2006-01-02T15:04:05Z07:00\" }}"
      - "--label=org.opencontainers.image.title={{ quote \"imuachain\" }}"
      - "--label=org.opencontainers.image.description='{{ quote \"IMUA full node (release image)\" }}"

  - id: ghcr-arm64
    skip_push: "{{ .IsSnapshot }}"
    use: buildx
    dockerfile: Dockerfile.ci
    ids: [imuad-linux-arm64]
    image_templates:
      - "ghcr.io/imua-xyz/imuachain:{{ .Tag }}-arm64"
      - '{{ if not (contains .Tag "-") }}ghcr.io/imua-xyz/imuachain:latest-arm64{{ end }}'
    goos: linux
    goarch: arm64
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.source={{ .GitURL }}"
      - "--label=org.opencontainers.image.revision={{ .Commit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.created={{ time \"2006-01-02T15:04:05Z07:00\" }}"
      - "--label=org.opencontainers.image.title={{ quote \"imuachain\" }}"
      - "--label=org.opencontainers.image.description='{{ quote \"IMUA full node (release image)\" }}"

docker_manifests:
  - name_template: "ghcr.io/imua-xyz/imuachain:{{ .Tag }}"
    skip_push: "{{ .IsSnapshot }}"
    image_templates:
      - "ghcr.io/imua-xyz/imuachain:{{ .Tag }}-amd64"
      - "ghcr.io/imua-xyz/imuachain:{{ .Tag }}-arm64"

  - name_template: "ghcr.io/imua-xyz/imuachain:latest"
    skip_push: '{{ or .IsSnapshot (contains .Tag "-")}}'
    image_templates:
      - "ghcr.io/imua-xyz/imuachain:{{ .Tag }}-amd64"
      - "ghcr.io/imua-xyz/imuachain:{{ .Tag }}-arm64"
