package types

const (
	EventTypeCreatePrice        = "create_price"
	EventTypeOracleLiveness     = "oracle_liveness"
	EventTypeOracleSlash        = "oracle_slash"
	EventTypeOracleUpdateParams = "oracle_update_params"
	EventTypeXChainDelivery     = "xchain_delivery"
	EventTypeXChainBatch        = "xchain_batch"

	AttributeKeyFeederID         = "feeder_id"
	AttributeKeyTokenID          = "token_id"
	AttributeKeyBasedBlock       = "based_block"
	AttributeKeyRoundID          = "round_id"
	AttributeKeyProposer         = "proposer"
	AttributeKeyFinalPrice       = "final_price"
	AttributeKeyPriceUpdated     = "price_update"
	AttributeKeyParamsUpdated    = "params_update"
	AttributeKeyFeederIDs        = "feeder_ids"
	AttributeKeyNSTStakersUpdate = "nst_stakers_update"
	AttributeKeyNSTStakersChange = "nst_stakers_change"
	AttributeKeyNSTBalanceUpdate = "nst_balance_update"
	AttributeKeyNSTBalanceChange = "nst_balance_change"
	AttributeKeyNSTPieceUpdate   = "nst_piece_update"
	AttributeKeyNSTPieceChange   = "nst_piece_Change"
	AttributeKeyNSTVersionUpdate = "nst_version_update"
	AttributeKeyNSTFeedVersion   = "nst_feed_version"
	// xchain post-aggregation attributes
	AttributeKeyXChainSrcChainID = "xchain_src_chain_id"
	AttributeKeyXChainBatchSeq   = "xchain_batch_seq"
	AttributeKeyXChainMsgCount   = "xchain_msg_count"
	AttributeKeyXChainRootHash   = "xchain_root_hash"
	// xchain budgeted delivery attributes
	AttributeKeyXChainMsgID        = "xchain_msg_id"
	AttributeKeyXChainPayloadBytes = "xchain_payload_bytes"
	AttributeKeyXChainRetryCount   = "xchain_retry_count"
	AttributeKeyValidatorKey       = "validator_key"
	AttributeKeyMissedRounds       = "missed_rounds"
	AttributeKeyHeight             = "height"
	AttributeKeyPower              = "power"
	AttributeKeyReason             = "reason"
	AttributeKeyJailed             = "jailed"
	AttributeKeyBurnedCoins        = "burned_coins"

	AttributeValueTrue                 = "true"
	AttributeValueSuccess              = "success"
	AttributeValueFalse                = "false"
	AttributeValueNativeTokenDeposit   = "deposit"
	AttributeValueNativeTokenWithdraw  = "withdraw"
	AttributeValueMissingReportPrice   = "missing_report_price"
	AttributeValueMaliciousReportPrice = "malicious_report_price"
	AttributeValueMaliciousReportPiece = "malicious_report_piece"
)
