// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: imuachain/oracle/v1/native_token.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Action defines the reason the balance changed
type Action int32

const (
	// balance updated when a new round generated
	Action_ACTION_ROUND_UNSPECIFIED Action = 0
	// balance updated when a deposit happened
	Action_ACTION_DEPOSIT Action = 1
	// balance updated when a withdraw happened
	Action_ACTION_WITHDRAW Action = 2
	// balance updatd when a slah/refund on beacon chain happened
	Action_ACTION_SLASH_REFUND Action = 3
)

var Action_name = map[int32]string{
	0: "ACTION_ROUND_UNSPECIFIED",
	1: "ACTION_DEPOSIT",
	2: "ACTION_WITHDRAW",
	3: "ACTION_SLASH_REFUND",
}

var Action_value = map[string]int32{
	"ACTION_ROUND_UNSPECIFIED": 0,
	"ACTION_DEPOSIT":           1,
	"ACTION_WITHDRAW":          2,
	"ACTION_SLASH_REFUND":      3,
}

func (x Action) String() string {
	return proto.EnumName(Action_name, int32(x))
}

func (Action) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_defbc9a40b211816, []int{0}
}

// BalanceInfo tells effective-balance for native-restaking asset
type BalanceInfo struct {
	// current round of price, this is updated based on tokenFeeder
	RoundID uint64 `protobuf:"varint,1,opt,name=round_id,json=roundId,proto3" json:"round_id,omitempty"`
	// on which block the balance updated, deposit/withdraw will update this and round_id might not change
	Block uint64 `protobuf:"varint,2,opt,name=block,proto3" json:"block,omitempty"`
	// index used to distinguish multiple balanceInfo for one same roundid
	Index uint64 `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
	// beaconchain epoch related to slash_refund
	// uint epoch = 3;
	Balance uint64 `protobuf:"varint,4,opt,name=balance,proto3" json:"balance,omitempty"`
	// change tells the reason balance changed
	Change Action `protobuf:"varint,5,opt,name=change,proto3,enum=imuachain.oracle.v1.Action" json:"change,omitempty"`
}

func (m *BalanceInfo) Reset()         { *m = BalanceInfo{} }
func (m *BalanceInfo) String() string { return proto.CompactTextString(m) }
func (*BalanceInfo) ProtoMessage()    {}
func (*BalanceInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_defbc9a40b211816, []int{0}
}
func (m *BalanceInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BalanceInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BalanceInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BalanceInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BalanceInfo.Merge(m, src)
}
func (m *BalanceInfo) XXX_Size() int {
	return m.Size()
}
func (m *BalanceInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BalanceInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BalanceInfo proto.InternalMessageInfo

func (m *BalanceInfo) GetRoundID() uint64 {
	if m != nil {
		return m.RoundID
	}
	return 0
}

func (m *BalanceInfo) GetBlock() uint64 {
	if m != nil {
		return m.Block
	}
	return 0
}

func (m *BalanceInfo) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *BalanceInfo) GetBalance() uint64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *BalanceInfo) GetChange() Action {
	if m != nil {
		return m.Change
	}
	return Action_ACTION_ROUND_UNSPECIFIED
}

// StakerInfo represents all related information for a staker of native-restaking
type StakerInfo struct {
	// staker's address
	StakerAddr string `protobuf:"bytes,1,opt,name=staker_addr,json=stakerAddr,proto3" json:"staker_addr,omitempty"`
	// the index of corresponding staker in staker list
	StakerIndex uint32 `protobuf:"varint,2,opt,name=staker_index,json=stakerIndex,proto3" json:"staker_index,omitempty"`
	// list of validators that this staker corresponding to on beacon chain
	ValidatorList []*ValidatorDeposit `protobuf:"bytes,3,rep,name=validator_list,json=validatorList,proto3" json:"validator_list,omitempty"`
	// list of balances to represets the history of this staker
	BalanceList []*BalanceInfo `protobuf:"bytes,4,rep,name=balance_list,json=balanceList,proto3" json:"balance_list,omitempty"`
}

func (m *StakerInfo) Reset()         { *m = StakerInfo{} }
func (m *StakerInfo) String() string { return proto.CompactTextString(m) }
func (*StakerInfo) ProtoMessage()    {}
func (*StakerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_defbc9a40b211816, []int{1}
}
func (m *StakerInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StakerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StakerInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StakerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StakerInfo.Merge(m, src)
}
func (m *StakerInfo) XXX_Size() int {
	return m.Size()
}
func (m *StakerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_StakerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_StakerInfo proto.InternalMessageInfo

func (m *StakerInfo) GetStakerAddr() string {
	if m != nil {
		return m.StakerAddr
	}
	return ""
}

func (m *StakerInfo) GetStakerIndex() uint32 {
	if m != nil {
		return m.StakerIndex
	}
	return 0
}

func (m *StakerInfo) GetValidatorList() []*ValidatorDeposit {
	if m != nil {
		return m.ValidatorList
	}
	return nil
}

func (m *StakerInfo) GetBalanceList() []*BalanceInfo {
	if m != nil {
		return m.BalanceList
	}
	return nil
}

// StakerList defines the list of stakers
type StakerList struct {
	// list of staker's address
	StakerAddrs []string `protobuf:"bytes,1,rep,name=staker_addrs,json=stakerAddrs,proto3" json:"staker_addrs,omitempty"`
}

func (m *StakerList) Reset()         { *m = StakerList{} }
func (m *StakerList) String() string { return proto.CompactTextString(m) }
func (*StakerList) ProtoMessage()    {}
func (*StakerList) Descriptor() ([]byte, []int) {
	return fileDescriptor_defbc9a40b211816, []int{2}
}
func (m *StakerList) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StakerList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StakerList.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StakerList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StakerList.Merge(m, src)
}
func (m *StakerList) XXX_Size() int {
	return m.Size()
}
func (m *StakerList) XXX_DiscardUnknown() {
	xxx_messageInfo_StakerList.DiscardUnknown(m)
}

var xxx_messageInfo_StakerList proto.InternalMessageInfo

func (m *StakerList) GetStakerAddrs() []string {
	if m != nil {
		return m.StakerAddrs
	}
	return nil
}

// Staker defines the basic info of a staker without address and balance history.
// Used for compact representation when full StakerInfo is not needed.
type Staker struct {
	// staker's index
	StakerIndex uint32 `protobuf:"varint,1,opt,name=staker_index,json=stakerIndex,proto3" json:"staker_index,omitempty"`
	// validtor_list is the list of validators that this staker corresponding to on beacon chain
	ValidatorList []*ValidatorDeposit `protobuf:"bytes,2,rep,name=validator_list,json=validatorList,proto3" json:"validator_list,omitempty"`
}

func (m *Staker) Reset()         { *m = Staker{} }
func (m *Staker) String() string { return proto.CompactTextString(m) }
func (*Staker) ProtoMessage()    {}
func (*Staker) Descriptor() ([]byte, []int) {
	return fileDescriptor_defbc9a40b211816, []int{3}
}
func (m *Staker) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Staker) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Staker.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Staker) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Staker.Merge(m, src)
}
func (m *Staker) XXX_Size() int {
	return m.Size()
}
func (m *Staker) XXX_DiscardUnknown() {
	xxx_messageInfo_Staker.DiscardUnknown(m)
}

var xxx_messageInfo_Staker proto.InternalMessageInfo

func (m *Staker) GetStakerIndex() uint32 {
	if m != nil {
		return m.StakerIndex
	}
	return 0
}

func (m *Staker) GetValidatorList() []*ValidatorDeposit {
	if m != nil {
		return m.ValidatorList
	}
	return nil
}

// Balances defines the list of balanceInfo
type Balances struct {
	// list of balanceInfo
	BalanceList []*BalanceInfo `protobuf:"bytes,1,rep,name=balance_list,json=balanceList,proto3" json:"balance_list,omitempty"`
}

func (m *Balances) Reset()         { *m = Balances{} }
func (m *Balances) String() string { return proto.CompactTextString(m) }
func (*Balances) ProtoMessage()    {}
func (*Balances) Descriptor() ([]byte, []int) {
	return fileDescriptor_defbc9a40b211816, []int{4}
}
func (m *Balances) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Balances) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Balances.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Balances) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Balances.Merge(m, src)
}
func (m *Balances) XXX_Size() int {
	return m.Size()
}
func (m *Balances) XXX_DiscardUnknown() {
	xxx_messageInfo_Balances.DiscardUnknown(m)
}

var xxx_messageInfo_Balances proto.InternalMessageInfo

func (m *Balances) GetBalanceList() []*BalanceInfo {
	if m != nil {
		return m.BalanceList
	}
	return nil
}

// ValidatorDeposit defines the version of a validator
type ValidatorDeposit struct {
	// validator's public key on beacon chain
	ValidatorPubkey string `protobuf:"bytes,1,opt,name=validator_pubkey,json=validatorPubkey,proto3" json:"validator_pubkey,omitempty"`
	// version of the validator info (on deposit)
	Version uint64 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	// deposit amount of the validator
	DepositAmount uint64 `protobuf:"varint,3,opt,name=deposit_amount,json=depositAmount,proto3" json:"deposit_amount,omitempty"`
}

func (m *ValidatorDeposit) Reset()         { *m = ValidatorDeposit{} }
func (m *ValidatorDeposit) String() string { return proto.CompactTextString(m) }
func (*ValidatorDeposit) ProtoMessage()    {}
func (*ValidatorDeposit) Descriptor() ([]byte, []int) {
	return fileDescriptor_defbc9a40b211816, []int{5}
}
func (m *ValidatorDeposit) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ValidatorDeposit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ValidatorDeposit.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ValidatorDeposit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidatorDeposit.Merge(m, src)
}
func (m *ValidatorDeposit) XXX_Size() int {
	return m.Size()
}
func (m *ValidatorDeposit) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidatorDeposit.DiscardUnknown(m)
}

var xxx_messageInfo_ValidatorDeposit proto.InternalMessageInfo

func (m *ValidatorDeposit) GetValidatorPubkey() string {
	if m != nil {
		return m.ValidatorPubkey
	}
	return ""
}

func (m *ValidatorDeposit) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *ValidatorDeposit) GetDepositAmount() uint64 {
	if m != nil {
		return m.DepositAmount
	}
	return 0
}

// NSTVersion defines the version of native-staking token
type NSTVersion struct {
	// version of the nst info (on balance change, on deposit/withdraw)
	Version *VersionDepositAmount `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	// version of the nst info (on balance change, on deposit/withdraw) based on which price-feeder should submit balance change
	FeedVersion *VersionDepositAmount `protobuf:"bytes,2,opt,name=feed_version,json=feedVersion,proto3" json:"feed_version,omitempty"`
}

func (m *NSTVersion) Reset()         { *m = NSTVersion{} }
func (m *NSTVersion) String() string { return proto.CompactTextString(m) }
func (*NSTVersion) ProtoMessage()    {}
func (*NSTVersion) Descriptor() ([]byte, []int) {
	return fileDescriptor_defbc9a40b211816, []int{6}
}
func (m *NSTVersion) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *NSTVersion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_NSTVersion.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *NSTVersion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NSTVersion.Merge(m, src)
}
func (m *NSTVersion) XXX_Size() int {
	return m.Size()
}
func (m *NSTVersion) XXX_DiscardUnknown() {
	xxx_messageInfo_NSTVersion.DiscardUnknown(m)
}

var xxx_messageInfo_NSTVersion proto.InternalMessageInfo

func (m *NSTVersion) GetVersion() *VersionDepositAmount {
	if m != nil {
		return m.Version
	}
	return nil
}

func (m *NSTVersion) GetFeedVersion() *VersionDepositAmount {
	if m != nil {
		return m.FeedVersion
	}
	return nil
}

// VersionDepositAmount defines the version and deposit amount
type VersionDepositAmount struct {
	// version of the nst info (on balance change, on deposit/withdraw)
	Version uint64 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	// accumulated deposit amount
	DepositAmount uint64 `protobuf:"varint,2,opt,name=deposit_amount,json=depositAmount,proto3" json:"deposit_amount,omitempty"`
}

func (m *VersionDepositAmount) Reset()         { *m = VersionDepositAmount{} }
func (m *VersionDepositAmount) String() string { return proto.CompactTextString(m) }
func (*VersionDepositAmount) ProtoMessage()    {}
func (*VersionDepositAmount) Descriptor() ([]byte, []int) {
	return fileDescriptor_defbc9a40b211816, []int{7}
}
func (m *VersionDepositAmount) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *VersionDepositAmount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_VersionDepositAmount.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *VersionDepositAmount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionDepositAmount.Merge(m, src)
}
func (m *VersionDepositAmount) XXX_Size() int {
	return m.Size()
}
func (m *VersionDepositAmount) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionDepositAmount.DiscardUnknown(m)
}

var xxx_messageInfo_VersionDepositAmount proto.InternalMessageInfo

func (m *VersionDepositAmount) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *VersionDepositAmount) GetDepositAmount() uint64 {
	if m != nil {
		return m.DepositAmount
	}
	return 0
}

func init() {
	proto.RegisterEnum("imuachain.oracle.v1.Action", Action_name, Action_value)
	proto.RegisterType((*BalanceInfo)(nil), "imuachain.oracle.v1.BalanceInfo")
	proto.RegisterType((*StakerInfo)(nil), "imuachain.oracle.v1.StakerInfo")
	proto.RegisterType((*StakerList)(nil), "imuachain.oracle.v1.StakerList")
	proto.RegisterType((*Staker)(nil), "imuachain.oracle.v1.Staker")
	proto.RegisterType((*Balances)(nil), "imuachain.oracle.v1.Balances")
	proto.RegisterType((*ValidatorDeposit)(nil), "imuachain.oracle.v1.ValidatorDeposit")
	proto.RegisterType((*NSTVersion)(nil), "imuachain.oracle.v1.NSTVersion")
	proto.RegisterType((*VersionDepositAmount)(nil), "imuachain.oracle.v1.VersionDepositAmount")
}

func init() {
	proto.RegisterFile("imuachain/oracle/v1/native_token.proto", fileDescriptor_defbc9a40b211816)
}

var fileDescriptor_defbc9a40b211816 = []byte{
	// 624 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xdf, 0x4e, 0x1a, 0x4f,
	0x14, 0x66, 0x40, 0x51, 0xcf, 0x2a, 0x92, 0xd1, 0xe4, 0xb7, 0xf9, 0xb5, 0x41, 0xba, 0x89, 0x06,
	0x9b, 0x96, 0x8d, 0xfa, 0x04, 0xc8, 0x62, 0xdc, 0x84, 0x80, 0x59, 0x50, 0x93, 0xde, 0x6c, 0x96,
	0xdd, 0x11, 0x36, 0xe0, 0x0e, 0xd9, 0x1d, 0x88, 0xf4, 0xa2, 0xcf, 0xd0, 0x37, 0xe8, 0x2b, 0xf4,
	0x31, 0x7a, 0xe9, 0x65, 0xaf, 0x9a, 0x06, 0x5e, 0xa4, 0x99, 0x3f, 0x08, 0xa9, 0x24, 0x6d, 0xbd,
	0xe3, 0x7c, 0xe7, 0x3b, 0xdf, 0xf9, 0xbe, 0x61, 0x76, 0xe0, 0x28, 0xbc, 0x1f, 0x79, 0x7e, 0xcf,
	0x0b, 0x23, 0x93, 0xc6, 0x9e, 0x3f, 0x20, 0xe6, 0xf8, 0xc4, 0x8c, 0x3c, 0x16, 0x8e, 0x89, 0xcb,
	0x68, 0x9f, 0x44, 0xe5, 0x61, 0x4c, 0x19, 0xc5, 0x7b, 0x4f, 0xbc, 0xb2, 0xe4, 0x95, 0xc7, 0x27,
	0xff, 0xef, 0x77, 0x69, 0x97, 0x8a, 0xbe, 0xc9, 0x7f, 0x49, 0xaa, 0xf1, 0x15, 0x81, 0x76, 0xee,
	0x0d, 0xbc, 0xc8, 0x27, 0x76, 0x74, 0x47, 0xf1, 0x11, 0x6c, 0xc6, 0x74, 0x14, 0x05, 0x6e, 0x18,
	0xe8, 0xa8, 0x88, 0x4a, 0x6b, 0xe7, 0xda, 0xf4, 0xc7, 0xc1, 0x86, 0xc3, 0x31, 0xdb, 0x72, 0x36,
	0x44, 0xd3, 0x0e, 0xf0, 0x3e, 0xac, 0x77, 0x06, 0xd4, 0xef, 0xeb, 0x69, 0x4e, 0x72, 0x64, 0xc1,
	0xd1, 0x30, 0x0a, 0xc8, 0x83, 0x9e, 0x91, 0xa8, 0x28, 0xb0, 0x0e, 0x1b, 0x1d, 0xb9, 0x42, 0x5f,
	0x13, 0xf8, 0xbc, 0xc4, 0x67, 0x90, 0xf5, 0x7b, 0x5e, 0xd4, 0x25, 0xfa, 0x7a, 0x11, 0x95, 0x72,
	0xa7, 0xaf, 0xca, 0x2b, 0x9c, 0x97, 0x2b, 0x3e, 0x0b, 0x69, 0xe4, 0x28, 0xaa, 0x31, 0x43, 0x00,
	0x2d, 0xe6, 0xf5, 0x49, 0x2c, 0x1c, 0x1f, 0x80, 0x96, 0x88, 0xca, 0xf5, 0x82, 0x20, 0x16, 0xa6,
	0xb7, 0x1c, 0x90, 0x50, 0x25, 0x08, 0x62, 0xfc, 0x06, 0xb6, 0x15, 0x41, 0x7a, 0xe3, 0x8e, 0x77,
	0x1c, 0x35, 0x64, 0x0b, 0x87, 0x75, 0xc8, 0x8d, 0xbd, 0x41, 0x18, 0x78, 0x8c, 0xc6, 0xee, 0x20,
	0x4c, 0x98, 0x9e, 0x29, 0x66, 0x4a, 0xda, 0xe9, 0xe1, 0x4a, 0x3f, 0x37, 0x73, 0xaa, 0x45, 0x86,
	0x34, 0x09, 0x99, 0xb3, 0xf3, 0x34, 0x5c, 0x0f, 0x13, 0x86, 0xab, 0xb0, 0xad, 0x02, 0x4a, 0xad,
	0x35, 0xa1, 0x55, 0x5c, 0xa9, 0xb5, 0x74, 0xf6, 0x8e, 0xa6, 0xa6, 0xb8, 0x88, 0x61, 0xce, 0x43,
	0x0a, 0xc9, 0x45, 0x06, 0x1e, 0x32, 0xd1, 0x51, 0x31, 0x53, 0xda, 0x9a, 0x67, 0xe0, 0x29, 0x13,
	0x63, 0x02, 0x59, 0x39, 0xf0, 0x2c, 0x30, 0xfa, 0x9b, 0xc0, 0xe9, 0x97, 0x07, 0x36, 0x9a, 0xb0,
	0xa9, 0x72, 0x24, 0xcf, 0xc2, 0xa3, 0x97, 0x84, 0xff, 0x04, 0xf9, 0xdf, 0x77, 0xe2, 0x63, 0xc8,
	0x2f, 0x2c, 0x0f, 0x47, 0x9d, 0x3e, 0x99, 0xa8, 0x3f, 0x7b, 0xf7, 0x09, 0xbf, 0x12, 0x30, 0xbf,
	0x70, 0x63, 0x12, 0x27, 0x21, 0x8d, 0xd4, 0xf5, 0x9c, 0x97, 0xf8, 0x10, 0x72, 0x81, 0xd4, 0x73,
	0xbd, 0x7b, 0x3a, 0x8a, 0x98, 0xba, 0xa9, 0x3b, 0x0a, 0xad, 0x08, 0xd0, 0xf8, 0x82, 0x00, 0x1a,
	0xad, 0xf6, 0x8d, 0x9a, 0xaa, 0x2e, 0xf4, 0xf8, 0x46, 0xed, 0xf4, 0x78, 0xf5, 0x31, 0x49, 0x8e,
	0xb5, 0x2c, 0xb5, 0x58, 0x5d, 0x87, 0xed, 0x3b, 0x42, 0x02, 0x77, 0xd9, 0xd9, 0x3f, 0x29, 0x69,
	0x7c, 0x5c, 0x75, 0x8c, 0x5b, 0xd8, 0x5f, 0x45, 0x5a, 0x8e, 0x8e, 0xfe, 0x14, 0x3d, 0xbd, 0x22,
	0xfa, 0xdb, 0x1e, 0x64, 0xe5, 0xf7, 0x86, 0x5f, 0x83, 0x5e, 0xa9, 0xb6, 0xed, 0x66, 0xc3, 0x75,
	0x9a, 0xd7, 0x0d, 0xcb, 0xbd, 0x6e, 0xb4, 0xae, 0x6a, 0x55, 0xfb, 0xc2, 0xae, 0x59, 0xf9, 0x14,
	0xc6, 0x90, 0x53, 0x5d, 0xab, 0x76, 0xd5, 0x6c, 0xd9, 0xed, 0x3c, 0xc2, 0x7b, 0xb0, 0xab, 0xb0,
	0x5b, 0xbb, 0x7d, 0x69, 0x39, 0x95, 0xdb, 0x7c, 0x1a, 0xff, 0x07, 0x7b, 0x0a, 0x6c, 0xd5, 0x2b,
	0xad, 0x4b, 0xd7, 0xa9, 0x5d, 0x5c, 0x37, 0xac, 0x7c, 0xe6, 0xfc, 0xe2, 0xdb, 0xb4, 0x80, 0x1e,
	0xa7, 0x05, 0xf4, 0x73, 0x5a, 0x40, 0x9f, 0x67, 0x85, 0xd4, 0xe3, 0xac, 0x90, 0xfa, 0x3e, 0x2b,
	0xa4, 0x3e, 0xbc, 0xeb, 0x86, 0xac, 0x37, 0xea, 0x94, 0x7d, 0x7a, 0x6f, 0xf2, 0xe3, 0x79, 0xff,
	0x30, 0xf9, 0x68, 0x2e, 0xde, 0xbe, 0x87, 0xf9, 0xeb, 0xc7, 0x26, 0x43, 0x92, 0x74, 0xb2, 0xe2,
	0x25, 0x3b, 0xfb, 0x15, 0x00, 0x00, 0xff, 0xff, 0xe8, 0xbe, 0x60, 0xd9, 0x1e, 0x05, 0x00, 0x00,
}

func (m *BalanceInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BalanceInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BalanceInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Change != 0 {
		i = encodeVarintNativeToken(dAtA, i, uint64(m.Change))
		i--
		dAtA[i] = 0x28
	}
	if m.Balance != 0 {
		i = encodeVarintNativeToken(dAtA, i, uint64(m.Balance))
		i--
		dAtA[i] = 0x20
	}
	if m.Index != 0 {
		i = encodeVarintNativeToken(dAtA, i, uint64(m.Index))
		i--
		dAtA[i] = 0x18
	}
	if m.Block != 0 {
		i = encodeVarintNativeToken(dAtA, i, uint64(m.Block))
		i--
		dAtA[i] = 0x10
	}
	if m.RoundID != 0 {
		i = encodeVarintNativeToken(dAtA, i, uint64(m.RoundID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *StakerInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StakerInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StakerInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.BalanceList) > 0 {
		for iNdEx := len(m.BalanceList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.BalanceList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintNativeToken(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.ValidatorList) > 0 {
		for iNdEx := len(m.ValidatorList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ValidatorList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintNativeToken(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.StakerIndex != 0 {
		i = encodeVarintNativeToken(dAtA, i, uint64(m.StakerIndex))
		i--
		dAtA[i] = 0x10
	}
	if len(m.StakerAddr) > 0 {
		i -= len(m.StakerAddr)
		copy(dAtA[i:], m.StakerAddr)
		i = encodeVarintNativeToken(dAtA, i, uint64(len(m.StakerAddr)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *StakerList) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StakerList) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StakerList) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.StakerAddrs) > 0 {
		for iNdEx := len(m.StakerAddrs) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.StakerAddrs[iNdEx])
			copy(dAtA[i:], m.StakerAddrs[iNdEx])
			i = encodeVarintNativeToken(dAtA, i, uint64(len(m.StakerAddrs[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *Staker) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Staker) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Staker) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ValidatorList) > 0 {
		for iNdEx := len(m.ValidatorList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ValidatorList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintNativeToken(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if m.StakerIndex != 0 {
		i = encodeVarintNativeToken(dAtA, i, uint64(m.StakerIndex))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Balances) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Balances) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Balances) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.BalanceList) > 0 {
		for iNdEx := len(m.BalanceList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.BalanceList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintNativeToken(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *ValidatorDeposit) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ValidatorDeposit) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ValidatorDeposit) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.DepositAmount != 0 {
		i = encodeVarintNativeToken(dAtA, i, uint64(m.DepositAmount))
		i--
		dAtA[i] = 0x18
	}
	if m.Version != 0 {
		i = encodeVarintNativeToken(dAtA, i, uint64(m.Version))
		i--
		dAtA[i] = 0x10
	}
	if len(m.ValidatorPubkey) > 0 {
		i -= len(m.ValidatorPubkey)
		copy(dAtA[i:], m.ValidatorPubkey)
		i = encodeVarintNativeToken(dAtA, i, uint64(len(m.ValidatorPubkey)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *NSTVersion) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NSTVersion) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *NSTVersion) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.FeedVersion != nil {
		{
			size, err := m.FeedVersion.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintNativeToken(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.Version != nil {
		{
			size, err := m.Version.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintNativeToken(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *VersionDepositAmount) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VersionDepositAmount) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *VersionDepositAmount) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.DepositAmount != 0 {
		i = encodeVarintNativeToken(dAtA, i, uint64(m.DepositAmount))
		i--
		dAtA[i] = 0x10
	}
	if m.Version != 0 {
		i = encodeVarintNativeToken(dAtA, i, uint64(m.Version))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintNativeToken(dAtA []byte, offset int, v uint64) int {
	offset -= sovNativeToken(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *BalanceInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.RoundID != 0 {
		n += 1 + sovNativeToken(uint64(m.RoundID))
	}
	if m.Block != 0 {
		n += 1 + sovNativeToken(uint64(m.Block))
	}
	if m.Index != 0 {
		n += 1 + sovNativeToken(uint64(m.Index))
	}
	if m.Balance != 0 {
		n += 1 + sovNativeToken(uint64(m.Balance))
	}
	if m.Change != 0 {
		n += 1 + sovNativeToken(uint64(m.Change))
	}
	return n
}

func (m *StakerInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.StakerAddr)
	if l > 0 {
		n += 1 + l + sovNativeToken(uint64(l))
	}
	if m.StakerIndex != 0 {
		n += 1 + sovNativeToken(uint64(m.StakerIndex))
	}
	if len(m.ValidatorList) > 0 {
		for _, e := range m.ValidatorList {
			l = e.Size()
			n += 1 + l + sovNativeToken(uint64(l))
		}
	}
	if len(m.BalanceList) > 0 {
		for _, e := range m.BalanceList {
			l = e.Size()
			n += 1 + l + sovNativeToken(uint64(l))
		}
	}
	return n
}

func (m *StakerList) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.StakerAddrs) > 0 {
		for _, s := range m.StakerAddrs {
			l = len(s)
			n += 1 + l + sovNativeToken(uint64(l))
		}
	}
	return n
}

func (m *Staker) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.StakerIndex != 0 {
		n += 1 + sovNativeToken(uint64(m.StakerIndex))
	}
	if len(m.ValidatorList) > 0 {
		for _, e := range m.ValidatorList {
			l = e.Size()
			n += 1 + l + sovNativeToken(uint64(l))
		}
	}
	return n
}

func (m *Balances) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.BalanceList) > 0 {
		for _, e := range m.BalanceList {
			l = e.Size()
			n += 1 + l + sovNativeToken(uint64(l))
		}
	}
	return n
}

func (m *ValidatorDeposit) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ValidatorPubkey)
	if l > 0 {
		n += 1 + l + sovNativeToken(uint64(l))
	}
	if m.Version != 0 {
		n += 1 + sovNativeToken(uint64(m.Version))
	}
	if m.DepositAmount != 0 {
		n += 1 + sovNativeToken(uint64(m.DepositAmount))
	}
	return n
}

func (m *NSTVersion) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Version != nil {
		l = m.Version.Size()
		n += 1 + l + sovNativeToken(uint64(l))
	}
	if m.FeedVersion != nil {
		l = m.FeedVersion.Size()
		n += 1 + l + sovNativeToken(uint64(l))
	}
	return n
}

func (m *VersionDepositAmount) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Version != 0 {
		n += 1 + sovNativeToken(uint64(m.Version))
	}
	if m.DepositAmount != 0 {
		n += 1 + sovNativeToken(uint64(m.DepositAmount))
	}
	return n
}

func sovNativeToken(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozNativeToken(x uint64) (n int) {
	return sovNativeToken(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *BalanceInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowNativeToken
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BalanceInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BalanceInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RoundID", wireType)
			}
			m.RoundID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNativeToken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RoundID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Block", wireType)
			}
			m.Block = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNativeToken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Block |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			m.Index = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNativeToken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Index |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Balance", wireType)
			}
			m.Balance = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNativeToken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Balance |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Change", wireType)
			}
			m.Change = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNativeToken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Change |= Action(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipNativeToken(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthNativeToken
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *StakerInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowNativeToken
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StakerInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StakerInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StakerAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNativeToken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNativeToken
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNativeToken
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StakerAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StakerIndex", wireType)
			}
			m.StakerIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNativeToken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StakerIndex |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNativeToken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthNativeToken
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthNativeToken
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorList = append(m.ValidatorList, &ValidatorDeposit{})
			if err := m.ValidatorList[len(m.ValidatorList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BalanceList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNativeToken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthNativeToken
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthNativeToken
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BalanceList = append(m.BalanceList, &BalanceInfo{})
			if err := m.BalanceList[len(m.BalanceList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipNativeToken(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthNativeToken
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *StakerList) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowNativeToken
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StakerList: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StakerList: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StakerAddrs", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNativeToken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNativeToken
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNativeToken
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StakerAddrs = append(m.StakerAddrs, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipNativeToken(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthNativeToken
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Staker) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowNativeToken
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Staker: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Staker: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StakerIndex", wireType)
			}
			m.StakerIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNativeToken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StakerIndex |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNativeToken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthNativeToken
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthNativeToken
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorList = append(m.ValidatorList, &ValidatorDeposit{})
			if err := m.ValidatorList[len(m.ValidatorList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipNativeToken(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthNativeToken
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Balances) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowNativeToken
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Balances: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Balances: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BalanceList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNativeToken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthNativeToken
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthNativeToken
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BalanceList = append(m.BalanceList, &BalanceInfo{})
			if err := m.BalanceList[len(m.BalanceList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipNativeToken(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthNativeToken
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ValidatorDeposit) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowNativeToken
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ValidatorDeposit: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ValidatorDeposit: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorPubkey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNativeToken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNativeToken
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNativeToken
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorPubkey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Version", wireType)
			}
			m.Version = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNativeToken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Version |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DepositAmount", wireType)
			}
			m.DepositAmount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNativeToken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DepositAmount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipNativeToken(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthNativeToken
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *NSTVersion) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowNativeToken
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NSTVersion: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NSTVersion: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Version", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNativeToken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthNativeToken
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthNativeToken
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Version == nil {
				m.Version = &VersionDepositAmount{}
			}
			if err := m.Version.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeedVersion", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNativeToken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthNativeToken
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthNativeToken
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.FeedVersion == nil {
				m.FeedVersion = &VersionDepositAmount{}
			}
			if err := m.FeedVersion.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipNativeToken(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthNativeToken
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *VersionDepositAmount) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowNativeToken
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VersionDepositAmount: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VersionDepositAmount: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Version", wireType)
			}
			m.Version = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNativeToken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Version |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DepositAmount", wireType)
			}
			m.DepositAmount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNativeToken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DepositAmount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipNativeToken(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthNativeToken
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipNativeToken(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowNativeToken
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowNativeToken
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowNativeToken
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthNativeToken
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupNativeToken
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthNativeToken
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthNativeToken        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowNativeToken          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupNativeToken = fmt.Errorf("proto: unexpected end of group")
)
