// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: exocore/oracle/v1/params.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/protobuf/types/known/durationpb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ConsensusMode defines the consensus mode for the prices.
type ConsensusMode int32

const (
	// CONSENSUS_MODE_UNSPECIFIED defines an invalid mode.
	ConsensusModeUnspecified ConsensusMode = 0
	// CONSENSUS_MODE_ASAP defines the mode to get final price immediately when the voting power
	// exceeds the threshold.
	ConsensusModeASAP ConsensusMode = 1
)

var ConsensusMode_name = map[int32]string{
	0: "CONSENSUS_MODE_UNSPECIFIED",
	1: "CONSENSUS_MODE_ASAP",
}

var ConsensusMode_value = map[string]int32{
	"CONSENSUS_MODE_UNSPECIFIED": 0,
	"CONSENSUS_MODE_ASAP":        1,
}

func (x ConsensusMode) String() string {
	return proto.EnumName(ConsensusMode_name, int32(x))
}

func (ConsensusMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_72f39bba4594b794, []int{0}
}

// Params defines the parameters for the module.
type Params struct {
	// chains represents the blockchains info
	Chains []*Chain `protobuf:"bytes,1,rep,name=chains,proto3" json:"chains,omitempty"`
	// tokens info
	Tokens []*Token `protobuf:"bytes,2,rep,name=tokens,proto3" json:"tokens,omitempty"`
	// sources info from where the price data would be fetched
	Sources []*Source `protobuf:"bytes,3,rep,name=sources,proto3" json:"sources,omitempty"`
	// rules specified on how to decide the provided price source to be accept
	Rules []*RuleSource `protobuf:"bytes,4,rep,name=rules,proto3" json:"rules,omitempty"`
	// each tokenFeeder represents an active token whose price being updated
	TokenFeeders []*TokenFeeder `protobuf:"bytes,5,rep,name=token_feeders,json=tokenFeeders,proto3" json:"token_feeders,omitempty"`
	// for each round allow at most max_nonce transactions to be sent by one validator, [1,max_nonce]
	MaxNonce int32 `protobuf:"varint,6,opt,name=max_nonce,json=maxNonce,proto3" json:"max_nonce,omitempty"`
	// voting power need to reach more than threshold_a/threshold_b
	ThresholdA int32 `protobuf:"varint,7,opt,name=threshold_a,json=thresholdA,proto3" json:"threshold_a,omitempty"`
	// voting power need to reach more than threshold_a/threshold_b
	ThresholdB int32 `protobuf:"varint,8,opt,name=threshold_b,json=thresholdB,proto3" json:"threshold_b,omitempty"`
	// for v1, mode=1, get final price as soon as voting power reach threshold_a/threshold_b
	Mode ConsensusMode `protobuf:"varint,9,opt,name=mode,proto3,enum=exocore.oracle.v1.ConsensusMode" json:"mode,omitempty"`
	// for each round, a validator only allowed to provide at most max_det_id consecutive rounds of prices for DS
	MaxDetId int32 `protobuf:"varint,10,opt,name=max_det_id,json=maxDetId,proto3" json:"max_det_id,omitempty"`
	// for each token, only keep max_size_prices round of prices
	MaxSizePrices int32 `protobuf:"varint,11,opt,name=max_size_prices,json=maxSizePrices,proto3" json:"max_size_prices,omitempty"`
	// slashing defines the slashing related params
	Slashing *SlashingParams `protobuf:"bytes,12,opt,name=slashing,proto3" json:"slashing,omitempty"`
}

func (m *Params) Reset()      { *m = Params{} }
func (*Params) ProtoMessage() {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_72f39bba4594b794, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetChains() []*Chain {
	if m != nil {
		return m.Chains
	}
	return nil
}

func (m *Params) GetTokens() []*Token {
	if m != nil {
		return m.Tokens
	}
	return nil
}

func (m *Params) GetSources() []*Source {
	if m != nil {
		return m.Sources
	}
	return nil
}

func (m *Params) GetRules() []*RuleSource {
	if m != nil {
		return m.Rules
	}
	return nil
}

func (m *Params) GetTokenFeeders() []*TokenFeeder {
	if m != nil {
		return m.TokenFeeders
	}
	return nil
}

func (m *Params) GetMaxNonce() int32 {
	if m != nil {
		return m.MaxNonce
	}
	return 0
}

func (m *Params) GetThresholdA() int32 {
	if m != nil {
		return m.ThresholdA
	}
	return 0
}

func (m *Params) GetThresholdB() int32 {
	if m != nil {
		return m.ThresholdB
	}
	return 0
}

func (m *Params) GetMode() ConsensusMode {
	if m != nil {
		return m.Mode
	}
	return ConsensusModeUnspecified
}

func (m *Params) GetMaxDetId() int32 {
	if m != nil {
		return m.MaxDetId
	}
	return 0
}

func (m *Params) GetMaxSizePrices() int32 {
	if m != nil {
		return m.MaxSizePrices
	}
	return 0
}

func (m *Params) GetSlashing() *SlashingParams {
	if m != nil {
		return m.Slashing
	}
	return nil
}

// slashing related params
type SlashingParams struct {
	// reported_rounds_window defines how many rounds included in one window for performance review of missing report
	ReportedRoundsWindow int64 `protobuf:"varint,1,opt,name=reported_rounds_window,json=reportedRoundsWindow,proto3" json:"reported_rounds_window,omitempty"`
	// min_reported_perwindow defines at least how many rounds should be reported, this is a percentage of window
	MinReportedPerWindow github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,2,opt,name=min_reported_per_window,json=minReportedPerWindow,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"min_reported_per_window"`
	// oracle_miss_jail_duration defines the duration one validator should be jailed for missing reporting price
	OracleMissJailDuration time.Duration `protobuf:"bytes,3,opt,name=oracle_miss_jail_duration,json=oracleMissJailDuration,proto3,stdduration" json:"oracle_miss_jail_duration"`
	// oracle_malicious_jail_duration defines the duratin one validator should be jailed for malicious behavior
	OracleMaliciousJailDuration time.Duration `protobuf:"bytes,4,opt,name=oracle_malicious_jail_duration,json=oracleMaliciousJailDuration,proto3,stdduration" json:"oracle_malicious_jail_duration"`
	// slash_fraction_malicious defines the fraction one validator should be punished for malicious behavior
	SlashFractionMalicious github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,5,opt,name=slash_fraction_malicious,json=slashFractionMalicious,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"slash_fraction_malicious"`
}

func (m *SlashingParams) Reset()         { *m = SlashingParams{} }
func (m *SlashingParams) String() string { return proto.CompactTextString(m) }
func (*SlashingParams) ProtoMessage()    {}
func (*SlashingParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_72f39bba4594b794, []int{1}
}
func (m *SlashingParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SlashingParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SlashingParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SlashingParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SlashingParams.Merge(m, src)
}
func (m *SlashingParams) XXX_Size() int {
	return m.Size()
}
func (m *SlashingParams) XXX_DiscardUnknown() {
	xxx_messageInfo_SlashingParams.DiscardUnknown(m)
}

var xxx_messageInfo_SlashingParams proto.InternalMessageInfo

func (m *SlashingParams) GetReportedRoundsWindow() int64 {
	if m != nil {
		return m.ReportedRoundsWindow
	}
	return 0
}

func (m *SlashingParams) GetOracleMissJailDuration() time.Duration {
	if m != nil {
		return m.OracleMissJailDuration
	}
	return 0
}

func (m *SlashingParams) GetOracleMaliciousJailDuration() time.Duration {
	if m != nil {
		return m.OracleMaliciousJailDuration
	}
	return 0
}

func init() {
	proto.RegisterEnum("exocore.oracle.v1.ConsensusMode", ConsensusMode_name, ConsensusMode_value)
	proto.RegisterType((*Params)(nil), "exocore.oracle.v1.Params")
	proto.RegisterType((*SlashingParams)(nil), "exocore.oracle.v1.SlashingParams")
}

func init() { proto.RegisterFile("exocore/oracle/v1/params.proto", fileDescriptor_72f39bba4594b794) }

var fileDescriptor_72f39bba4594b794 = []byte{
	// 772 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x94, 0xbf, 0x4f, 0xc3, 0x46,
	0x14, 0xc7, 0x63, 0xf2, 0x03, 0xb8, 0x10, 0x0a, 0x57, 0x4a, 0x8f, 0x40, 0x1d, 0x17, 0x55, 0x28,
	0x42, 0xaa, 0x0d, 0x84, 0xa9, 0x6a, 0x07, 0xf2, 0x03, 0x09, 0x24, 0x42, 0xe4, 0x14, 0x55, 0xea,
	0x62, 0x39, 0xf6, 0x25, 0x39, 0xb0, 0x7d, 0xd1, 0x9d, 0x0d, 0x29, 0x6b, 0x97, 0x8a, 0xa9, 0x23,
	0x0b, 0x52, 0xa5, 0x2e, 0x1d, 0xbb, 0xf7, 0x1f, 0x60, 0x64, 0xac, 0x3a, 0xd0, 0x0a, 0x86, 0xfe,
	0x05, 0xdd, 0x2b, 0x9f, 0xed, 0x40, 0x42, 0x18, 0xda, 0x25, 0xf1, 0xbd, 0xef, 0xe7, 0xfb, 0xde,
	0xbb, 0xe7, 0x3b, 0x03, 0x19, 0x0f, 0xa9, 0x45, 0x19, 0xd6, 0x28, 0x33, 0x2d, 0x07, 0x6b, 0x97,
	0xbb, 0xda, 0xc0, 0x64, 0xa6, 0xcb, 0xd5, 0x01, 0xa3, 0x3e, 0x85, 0xcb, 0xb1, 0xae, 0x46, 0xba,
	0x7a, 0xb9, 0x5b, 0x5c, 0x36, 0x5d, 0xe2, 0x51, 0x4d, 0xfc, 0x46, 0x54, 0x71, 0xe3, 0x6d, 0x16,
	0xe2, 0x75, 0x13, 0xf5, 0xb3, 0xb7, 0xaa, 0x4f, 0x2f, 0xb0, 0x67, 0x74, 0x31, 0xb6, 0x31, 0x8b,
	0xa9, 0x95, 0x1e, 0xed, 0x51, 0xf1, 0xa8, 0x85, 0x4f, 0x71, 0x54, 0xee, 0x51, 0xda, 0x73, 0xb0,
	0x26, 0x56, 0x9d, 0xa0, 0xab, 0xd9, 0x01, 0x33, 0x7d, 0x42, 0xbd, 0x48, 0xdf, 0xfc, 0x2d, 0x03,
	0x72, 0x2d, 0xd1, 0x30, 0xdc, 0x01, 0x39, 0xab, 0x6f, 0x12, 0x8f, 0x23, 0x49, 0x49, 0x97, 0xf3,
	0x7b, 0x48, 0x7d, 0xd3, 0xbb, 0x5a, 0x0b, 0x01, 0x3d, 0xe6, 0x42, 0x87, 0x68, 0x84, 0xa3, 0x99,
	0x77, 0x1d, 0x5f, 0x87, 0x80, 0x1e, 0x73, 0xb0, 0x02, 0x66, 0x39, 0x0d, 0x98, 0x85, 0x39, 0x4a,
	0x0b, 0xcb, 0xda, 0x14, 0x4b, 0x5b, 0x10, 0x7a, 0x42, 0xc2, 0x0a, 0xc8, 0xb2, 0xc0, 0xc1, 0x1c,
	0x65, 0x84, 0xe5, 0x93, 0x29, 0x16, 0x3d, 0x70, 0x70, 0x6c, 0x8b, 0x58, 0x58, 0x03, 0x85, 0xd7,
	0x43, 0xe2, 0x28, 0x2b, 0xcc, 0xf2, 0x7b, 0x2d, 0x1e, 0x0a, 0x4c, 0x5f, 0xf0, 0x5f, 0x16, 0x1c,
	0xae, 0x83, 0x79, 0xd7, 0x1c, 0x1a, 0x1e, 0xf5, 0x2c, 0x8c, 0x72, 0x8a, 0x54, 0xce, 0xea, 0x73,
	0xae, 0x39, 0x6c, 0x86, 0x6b, 0x58, 0x02, 0x79, 0xbf, 0xcf, 0x30, 0xef, 0x53, 0xc7, 0x36, 0x4c,
	0x34, 0x2b, 0x64, 0x30, 0x0a, 0x1d, 0x8c, 0x03, 0x1d, 0x34, 0x37, 0x01, 0x54, 0xe1, 0x3e, 0xc8,
	0xb8, 0xd4, 0xc6, 0x68, 0x5e, 0x91, 0xca, 0x8b, 0x7b, 0xca, 0xb4, 0x79, 0x53, 0x8f, 0x63, 0x8f,
	0x07, 0xfc, 0x84, 0xda, 0x58, 0x17, 0x34, 0xdc, 0x00, 0x20, 0x6c, 0xca, 0xc6, 0xbe, 0x41, 0x6c,
	0x04, 0x46, 0x5d, 0xd5, 0xb1, 0x7f, 0x64, 0xc3, 0x2d, 0xf0, 0x41, 0xa8, 0x72, 0x72, 0x8d, 0x8d,
	0x01, 0x23, 0xe1, 0xa4, 0xf3, 0x02, 0x29, 0xb8, 0xe6, 0xb0, 0x4d, 0xae, 0x71, 0x4b, 0x04, 0xe1,
	0x57, 0x60, 0x8e, 0x3b, 0x26, 0xef, 0x13, 0xaf, 0x87, 0x16, 0x14, 0xa9, 0x9c, 0xdf, 0xfb, 0x74,
	0xda, 0xab, 0x88, 0x91, 0xe8, 0x88, 0xe8, 0x23, 0xcb, 0x17, 0x99, 0xdb, 0x9f, 0x4a, 0xa9, 0xcd,
	0x7f, 0xd2, 0x60, 0x71, 0x1c, 0x81, 0xfb, 0x60, 0x95, 0xe1, 0x01, 0x65, 0x3e, 0xb6, 0x0d, 0x46,
	0x03, 0xcf, 0xe6, 0xc6, 0x15, 0xf1, 0x6c, 0x7a, 0x85, 0x24, 0x45, 0x2a, 0xa7, 0xf5, 0x95, 0x44,
	0xd5, 0x85, 0xf8, 0x8d, 0xd0, 0xe0, 0x39, 0xf8, 0xd8, 0x25, 0x9e, 0x31, 0x72, 0x0e, 0x30, 0x4b,
	0x6c, 0x33, 0x8a, 0x54, 0x5e, 0xa8, 0x56, 0xee, 0x1f, 0x4b, 0xa9, 0x3f, 0x1e, 0x4b, 0x5b, 0x3d,
	0xe2, 0xf7, 0x83, 0x8e, 0x6a, 0x51, 0x57, 0xb3, 0x28, 0x77, 0x29, 0x8f, 0xff, 0x3e, 0xe7, 0xf6,
	0x85, 0xe6, 0x7f, 0x37, 0xc0, 0x5c, 0xad, 0x63, 0xeb, 0x97, 0xbf, 0x7f, 0xdd, 0x96, 0xf4, 0x15,
	0x97, 0x78, 0x7a, 0x9c, 0xb2, 0x85, 0x59, 0x5c, 0xcb, 0x02, 0x6b, 0xd1, 0x06, 0x0d, 0x97, 0x70,
	0x6e, 0x9c, 0x9b, 0xc4, 0x31, 0x92, 0x5b, 0x81, 0xd2, 0x62, 0x14, 0x6b, 0x6a, 0x74, 0x6d, 0xd4,
	0xe4, 0xda, 0xa8, 0xf5, 0x18, 0xa8, 0x16, 0xc2, 0x46, 0x6e, 0xff, 0x2c, 0x49, 0x51, 0x89, 0xd5,
	0x28, 0xd5, 0x09, 0xe1, 0xfc, 0xd8, 0x24, 0x4e, 0x82, 0x41, 0x17, 0xc8, 0x49, 0x11, 0xd3, 0x21,
	0x16, 0xa1, 0xc1, 0x64, 0xa5, 0xcc, 0x7f, 0xac, 0xb4, 0x1e, 0x57, 0x4a, 0xd2, 0x4d, 0x94, 0x43,
	0xe2, 0xd5, 0x18, 0x5d, 0x66, 0x5a, 0x61, 0xe4, 0xa5, 0x2c, 0xca, 0xfe, 0xff, 0x01, 0xae, 0x8a,
	0xa4, 0x87, 0x71, 0xce, 0x51, 0xe9, 0xed, 0xef, 0x25, 0x50, 0x18, 0x3b, 0x9a, 0xf0, 0x4b, 0x50,
	0xac, 0x9d, 0x36, 0xdb, 0x8d, 0x66, 0xfb, 0xac, 0x6d, 0x9c, 0x9c, 0xd6, 0x1b, 0xc6, 0x59, 0xb3,
	0xdd, 0x6a, 0xd4, 0x8e, 0x0e, 0x8f, 0x1a, 0xf5, 0xa5, 0x54, 0x71, 0xe3, 0xe6, 0x4e, 0x41, 0x63,
	0x96, 0x33, 0x8f, 0x0f, 0xb0, 0x45, 0xba, 0x04, 0xdb, 0x50, 0x05, 0x1f, 0x4e, 0xb8, 0x0f, 0xda,
	0x07, 0xad, 0x25, 0xa9, 0xf8, 0xd1, 0xcd, 0x9d, 0xb2, 0x3c, 0x66, 0x0b, 0x85, 0x62, 0xe6, 0x87,
	0x9f, 0xe5, 0x54, 0xf5, 0xf8, 0xfe, 0x49, 0x96, 0x1e, 0x9e, 0x64, 0xe9, 0xaf, 0x27, 0x59, 0xfa,
	0xf1, 0x59, 0x4e, 0x3d, 0x3c, 0xcb, 0xa9, 0xdf, 0x9f, 0xe5, 0xd4, 0xb7, 0x3b, 0xaf, 0x36, 0xd9,
	0x88, 0x0e, 0x75, 0x13, 0xfb, 0x57, 0x94, 0x5d, 0x68, 0xc9, 0xb7, 0x74, 0x98, 0x7c, 0x4d, 0xc5,
	0x96, 0x3b, 0x39, 0x31, 0xff, 0xca, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x24, 0x82, 0xa5, 0x31,
	0xd0, 0x05, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Slashing != nil {
		{
			size, err := m.Slashing.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintParams(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x62
	}
	if m.MaxSizePrices != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxSizePrices))
		i--
		dAtA[i] = 0x58
	}
	if m.MaxDetId != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxDetId))
		i--
		dAtA[i] = 0x50
	}
	if m.Mode != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.Mode))
		i--
		dAtA[i] = 0x48
	}
	if m.ThresholdB != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.ThresholdB))
		i--
		dAtA[i] = 0x40
	}
	if m.ThresholdA != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.ThresholdA))
		i--
		dAtA[i] = 0x38
	}
	if m.MaxNonce != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxNonce))
		i--
		dAtA[i] = 0x30
	}
	if len(m.TokenFeeders) > 0 {
		for iNdEx := len(m.TokenFeeders) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.TokenFeeders[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintParams(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.Rules) > 0 {
		for iNdEx := len(m.Rules) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Rules[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintParams(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.Sources) > 0 {
		for iNdEx := len(m.Sources) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Sources[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintParams(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Tokens) > 0 {
		for iNdEx := len(m.Tokens) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Tokens[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintParams(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Chains) > 0 {
		for iNdEx := len(m.Chains) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Chains[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintParams(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *SlashingParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SlashingParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SlashingParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.SlashFractionMalicious.Size()
		i -= size
		if _, err := m.SlashFractionMalicious.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	n2, err2 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(m.OracleMaliciousJailDuration, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.OracleMaliciousJailDuration):])
	if err2 != nil {
		return 0, err2
	}
	i -= n2
	i = encodeVarintParams(dAtA, i, uint64(n2))
	i--
	dAtA[i] = 0x22
	n3, err3 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(m.OracleMissJailDuration, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.OracleMissJailDuration):])
	if err3 != nil {
		return 0, err3
	}
	i -= n3
	i = encodeVarintParams(dAtA, i, uint64(n3))
	i--
	dAtA[i] = 0x1a
	{
		size := m.MinReportedPerWindow.Size()
		i -= size
		if _, err := m.MinReportedPerWindow.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if m.ReportedRoundsWindow != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.ReportedRoundsWindow))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Chains) > 0 {
		for _, e := range m.Chains {
			l = e.Size()
			n += 1 + l + sovParams(uint64(l))
		}
	}
	if len(m.Tokens) > 0 {
		for _, e := range m.Tokens {
			l = e.Size()
			n += 1 + l + sovParams(uint64(l))
		}
	}
	if len(m.Sources) > 0 {
		for _, e := range m.Sources {
			l = e.Size()
			n += 1 + l + sovParams(uint64(l))
		}
	}
	if len(m.Rules) > 0 {
		for _, e := range m.Rules {
			l = e.Size()
			n += 1 + l + sovParams(uint64(l))
		}
	}
	if len(m.TokenFeeders) > 0 {
		for _, e := range m.TokenFeeders {
			l = e.Size()
			n += 1 + l + sovParams(uint64(l))
		}
	}
	if m.MaxNonce != 0 {
		n += 1 + sovParams(uint64(m.MaxNonce))
	}
	if m.ThresholdA != 0 {
		n += 1 + sovParams(uint64(m.ThresholdA))
	}
	if m.ThresholdB != 0 {
		n += 1 + sovParams(uint64(m.ThresholdB))
	}
	if m.Mode != 0 {
		n += 1 + sovParams(uint64(m.Mode))
	}
	if m.MaxDetId != 0 {
		n += 1 + sovParams(uint64(m.MaxDetId))
	}
	if m.MaxSizePrices != 0 {
		n += 1 + sovParams(uint64(m.MaxSizePrices))
	}
	if m.Slashing != nil {
		l = m.Slashing.Size()
		n += 1 + l + sovParams(uint64(l))
	}
	return n
}

func (m *SlashingParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ReportedRoundsWindow != 0 {
		n += 1 + sovParams(uint64(m.ReportedRoundsWindow))
	}
	l = m.MinReportedPerWindow.Size()
	n += 1 + l + sovParams(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.OracleMissJailDuration)
	n += 1 + l + sovParams(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.OracleMaliciousJailDuration)
	n += 1 + l + sovParams(uint64(l))
	l = m.SlashFractionMalicious.Size()
	n += 1 + l + sovParams(uint64(l))
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Chains", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Chains = append(m.Chains, &Chain{})
			if err := m.Chains[len(m.Chains)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tokens", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Tokens = append(m.Tokens, &Token{})
			if err := m.Tokens[len(m.Tokens)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sources", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sources = append(m.Sources, &Source{})
			if err := m.Sources[len(m.Sources)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Rules", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Rules = append(m.Rules, &RuleSource{})
			if err := m.Rules[len(m.Rules)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TokenFeeders", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TokenFeeders = append(m.TokenFeeders, &TokenFeeder{})
			if err := m.TokenFeeders[len(m.TokenFeeders)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxNonce", wireType)
			}
			m.MaxNonce = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxNonce |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ThresholdA", wireType)
			}
			m.ThresholdA = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ThresholdA |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ThresholdB", wireType)
			}
			m.ThresholdB = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ThresholdB |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Mode", wireType)
			}
			m.Mode = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Mode |= ConsensusMode(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxDetId", wireType)
			}
			m.MaxDetId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxDetId |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxSizePrices", wireType)
			}
			m.MaxSizePrices = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxSizePrices |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Slashing", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Slashing == nil {
				m.Slashing = &SlashingParams{}
			}
			if err := m.Slashing.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SlashingParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SlashingParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SlashingParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReportedRoundsWindow", wireType)
			}
			m.ReportedRoundsWindow = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ReportedRoundsWindow |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinReportedPerWindow", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MinReportedPerWindow.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OracleMissJailDuration", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(&m.OracleMissJailDuration, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OracleMaliciousJailDuration", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(&m.OracleMaliciousJailDuration, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SlashFractionMalicious", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.SlashFractionMalicious.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
