name: "Consensus Warn"

on:
  # Only works on PRs, not on merge
  pull_request_target:
    types:
      - opened
      - synchronize

permissions:
  contents: read
  pull-requests: write

jobs:
  consensus-warn:
    permissions:
      contents: read
      pull-requests: write  # For reading the PR and posting comment
    runs-on: ubuntu-latest
    env:
      GOTOOLCHAIN: "go1.21.12"
    steps:
      # This is used for warning when a PR touches any of the roots, or any function or method directly or indirectly called by a root
      - uses: actions/checkout@v4
      - uses: orijtech/consensuswarn@956f047a43f56021a28afdfb2a2291a20955f48d
        with:
          # example.com/pkg/path.Type.Method
          roots: 'github.com/imua-xyz/imuachain/app.ImuachainApp.DeliverTx,github.com/imua-xyz/imuachain/app.ImuachainApp.BeginBlocker,github.com/imua-xyz/imuachain/app.ImuachainApp.EndBlocker'
